[package]
name = "engine"
version = "0.1.0"
edition = "2018"

[dependencies]
num_enum = "0.5.1"
rltk = { version = "0.8.7", features = ["serde"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
rand = "0.8.5"
lazy_static = "1.4.0"
shipyard = "0.6.2"
strum = "0.25"
strum_macros = "0.25"